apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bpdispatcher.fullname" . }}-secret
  labels:
    {{- include "bpdispatcher.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}